name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build SuperFreq (Windows)
      working-directory: ./SuperFreqCLI
      run: dotnet publish -c=Release --self-contained=false -r=win-x64
    - name: Build SuperFreq (Linux)
      working-directory: ./SuperFreqCLI
      run: dotnet publish -c=Release --self-contained=false -r=linux-x64
    - name: Create artifacts directories
      run: mkdir -p ./artifacts/superfreq_win_x64
    - run: mkdir -p ./artifacts/superfreq_linux_x64
    - name: Copy files for SuperFreq (Windows)
      run: cp ./SuperFreqCLI/bin/Release/netcoreapp3.0/win-x64/publish/* ./artifacts/superfreq_win_x64
    - name: Copy files for archive for SuperFreq (Linux)
      run: cp ./SuperFreqCLI/bin/Release/netcoreapp3.0/linux-x64/publish/* ./artifacts/superfreq_linux_x64
    - name: Creates artifact for SuperFreq (Windows)
      uses: actions/upload-artifact@master
      with:
        name: superfreq_win_x64
        path: ./artifacts/superfreq_win_x64/*
    - name: Creates artifact for SuperFreq (Linux)
      uses: actions/upload-artifact@master
      with:
        name: superfreq_linux_x64
        path: ./artifacts/superfreq_linux_x64/*
